version: '3.8'
services:
  nginx:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.app1.rule=Host(`app1.localhost`)
        - traefik.http.services.app1.loadbalancer.server.port=80
        # Activate https
        - traefik.http.routers.app1.tls=true
        - traefik.http.routers.app1.tls.certresolver=myresolver
        - traefik.http.routers.app1.middlewares=security@file
    networks:
      - gateway
      - default

networks:
  gateway:
    external: true
    name: gateway