version: '3.8'
services:
  nginx:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.app2.rule=Host(`app2.localhost`)
        - traefik.http.services.app2.loadbalancer.server.port=80
        # Activate https
        - traefik.http.routers.app2.tls=true
        - traefik.http.routers.app2.tls.certresolver=myresolver
        - traefik.http.routers.app2.middlewares=security@file
    networks:
      - gateway
      - default

networks:
  gateway:
    external: true
    name: gateway